//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literal
    {
        public Literal()
        {
            this.LiteralsAttackTypes = new HashSet<LiteralsAttackType>();
        }
    
        public int LiteralID { get; set; }
        public string Word { get; set; }
    
        public virtual ICollection<LiteralsAttackType> LiteralsAttackTypes { get; set; }
    }
}
