//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScanEntry
    {
        public ScanEntry()
        {
            this.ScanEntryPossibleAttackTypes = new HashSet<ScanEntryPossibleAttackType>();
        }
    
        public int ScanEntryID { get; set; }
        public string Content { get; set; }
        public bool InjectionAttackPossible { get; set; }
        public int ScanID { get; set; }
        public string Description { get; set; }
        public bool ActualPossiblity { get; set; }
    
        public virtual Scan Scan { get; set; }
        public virtual ICollection<ScanEntryPossibleAttackType> ScanEntryPossibleAttackTypes { get; set; }
    }
}
