//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scan
    {
        public Scan()
        {
            this.ScanEntries = new HashSet<ScanEntry>();
        }
    
        public int ScanID { get; set; }
        public System.DateTime Date { get; set; }
        public double DetectionRate { get; set; }
        public double DetectionAccuracy { get; set; }
        public double FalsePositiveRate { get; set; }
        public double FalseNegativeRate { get; set; }
        public int TotalBenign { get; set; }
        public int TotalMalicious { get; set; }
        public int TruePositive { get; set; }
        public int TrueNegative { get; set; }
        public int FalsePositive { get; set; }
        public int FalseNegative { get; set; }
    
        public virtual ICollection<ScanEntry> ScanEntries { get; set; }
    }
}
