//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLLiteralsEntities : DbContext
    {
        public SQLLiteralsEntities()
            : base("name=SQLLiteralsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttackType> AttackTypes { get; set; }
        public virtual DbSet<Literal> Literals { get; set; }
        public virtual DbSet<LiteralsAttackType> LiteralsAttackTypes { get; set; }
        public virtual DbSet<ScanEntry> ScanEntries { get; set; }
        public virtual DbSet<ScanEntryPossibleAttackType> ScanEntryPossibleAttackTypes { get; set; }
        public virtual DbSet<Scan> Scans { get; set; }
    }
}
